name: Check master Jitpack's dependency
on:
  push:
    branches:
      - master
jobs:
  check_jitpack_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache gradle wrapper
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlegradlewrapper-
      - name: Cache android cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-cache
          restore-keys: |
            ${{ runner.os }}-gradlegradlewrapper-
      - name: Use master dependencies in app
        run: |
          currentCommit=$(git rev-parse HEAD | cut -c1-10)
          perl -i -pe "s/project\(\"\:swissknife-core\"\)/\"com.github.xmartlabs.AndroidSwissKnife:swissknife-core:$currentCommit\"/gi" app/build.gradle
          perl -i -pe "s/project\(\"\:swissknife-datastore\"\)/\"com.github.xmartlabs.AndroidSwissKnife:swissknife-datastore:$currentCommit\"/gi" app/build.gradle
          perl -i -pe "s/project\(\"\:swissknife-navigation\"\)/\"com.github.xmartlabs.AndroidSwissKnife:swissknife-navigation:$currentCommit\"/gi" app/build.gradle
          perl -i -pe "s/project\(\"\:swissknife-navigation-debug\"\)/\"com.github.xmartlabs.AndroidSwissKnife:swissknife-navigation-debug:$currentCommit\"/gi" app/build.gradle
          perl -i -pe "s/project\(\"\:swissknife-reflection\"\)/\"com.github.xmartlabs.AndroidSwissKnife:swissknife-reflection:$currentCommit\"/gi" app/build.gradle
      - name: Build Sample app with master dependencies
        run: ./gradlew build -Dhttp.socketTimeout=100000 -Dhttp.connectionTimeout=100000 --refresh-dependencies
