name: Check and compile
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gradle cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache gradle wrapper
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlegradlewrapper-
      - name: Cache android cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.android/build-cache
          key: ${{ runner.os }}-android-cache
          restore-keys: |
            ${{ runner.os }}-gradlegradlewrapper-
      - name: Gradle Initialization
        run: ./gradlew
      - name: Detekt
        run: ./gradlew detekt
      - name: Upload Detekt report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Detekt report
          path: build/reports/detekt/detekt.html
      - name: Android Lints
        run: ./gradlew lint
      - name: Upload Lint report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Lints report
          path: app/build/reports/lint-results-devDebug.html
      - name: Build
        run: ./gradlew build
